######################################################################
# Automatically generated by qmake (2.01a) Fri May 19 14:07:54 2023
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += tetrixboard.h tetrixpiece.h tetrixwindow.h
SOURCES += main.cpp tetrixboard.cpp tetrixpiece.cpp tetrixwindow.cpp
